version: '3.8'

services:
  db:
    container_name: postgres_16
    image: postgres:16.1
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=test_db

